const fs = require("fs/promises");
const path = require("path");
const hre = require("hardhat");

const NETWORK_TO_CHAIN_ID = {
  amoy: 80002,
  localhost: 31337,
  hardhat: 31337
};

async function main() {
  const DocumentRegistry = await hre.ethers.getContractFactory("DocumentRegistry");
  const registry = await DocumentRegistry.deploy();
  await registry.waitForDeployment();

  const address = await registry.getAddress();
  const network = hre.network.name;
  const chainId = NETWORK_TO_CHAIN_ID[network] ?? Number(hre.network.config.chainId) ?? null;
  const deployment = {
    network,
    chainId,
    address,
    deployedAt: new Date().toISOString()
  };

  const deploymentsDir = path.join(__dirname, "..", "deployments");
  await fs.mkdir(deploymentsDir, { recursive: true });
  await fs.writeFile(
    path.join(deploymentsDir, `${network}.json`),
    JSON.stringify(deployment, null, 2)
  );

  // Also write a frontend-readable config so the static site picks up the
  // contract address without manual editing.
  const artifactPath = path.join(
    __dirname,
    "..",
    "artifacts",
    "contracts",
    "DocumentRegistry.sol",
    "DocumentRegistry.json"
  );
  const artifact = JSON.parse(await fs.readFile(artifactPath, "utf8"));
  const frontendConfig = {
    address,
    chainId,
    network,
    abi: artifact.abi
  };
  const frontendDir = path.join(__dirname, "..", "frontend");
  await fs.mkdir(frontendDir, { recursive: true });
  await fs.writeFile(
    path.join(frontendDir, "contract.js"),
    `// Auto-generated by scripts/deploy.js. Do not edit by hand.\n` +
      `window.CONTRACT_CONFIG = ${JSON.stringify(frontendConfig, null, 2)};\n`
  );

  console.log(`DocumentRegistry deployed to ${address} on ${network}`);
  console.log(`Wrote frontend/contract.js`);
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
